### ISSUE TITLE
`move-to()` ignores namespaces

### ISSUE THREAD

**Issue by aiwenar** [philschatz/css-plus#10]
Consider following

**HTML**
```html
<!doctype html>
<html>
    <a></a>
    <b>This is B</b>
    <c>This is C</c>
    <b xmlns="urn:test">This is a different B</b>
    <d xmlns="urn:test">This is D</d>
</html>
```

**CSS**
```css
@namespace test "urn:test";

a {
    content:
        parent-context(move-here('b'))
        parent-context(move-here('|c'))
        parent-context(move-here('test|d'));
}
```

Output (both for master and xml-files) is currently (cleaned)

```html
<html>
<body>
    <a>
        <b>This is B</b>
        <b xmlns="urn:test">This is a different B</b>
    </a>
    <c>This is C</c>
    <d xmlns="urn:test">This is D</d>
</body>
</html>
```

or, in other words, 

1. `move-to` treats `tag` selector as `*|tag`;
2. `|tag` never matches, even though it's equivalent to simply `tag`;
3. `namespace|tag` never matches
