### ISSUE TITLE
CSS Namespaces

### ISSUE THREAD

**Issue by aiwenar** [philschatz/css-plus#6]
**Example XHTML**
```xhtml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:test="urn:test">
    <test:test>
        <test:a>Hello!</test:a>
    </test:test>
</html>
```

**Example CSS**
```css
@namespace test "urn:test";
test|*::before {
  tag-name-set: div;
  content: "Hello!";
}
```

**Excepted result**
A div is inserted into every `test:*` element.

**Actual result**
Nothing is changed.
