### ISSUE TITLE
support namespaced elements

### ISSUE THREAD

**Issue by philschatz** [philschatz/css-plus#7]
```html
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:test="urn:test">
    <test:test>
        <test:a>Hello!</test:a>
    </test:test>
</html>
```

```css
@namespace test "urn:test";
test|*::before {
  tag-name-set: div;
  content: "Hello!";
}
```
